# =============================================================================
# SSH key pair — generated by Terraform, private key saved as payroll-mail-service.pem
# =============================================================================

resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = "payroll-mail-service-${var.environment}"
  public_key = tls_private_key.this.public_key_openssh
}

# Saved next to main.tf — chmod 600 applied automatically.
resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.this.private_key_pem
  filename        = "${path.module}/payroll-mail-service.pem"
  file_permission = "0600"
}

# =============================================================================
# Security group
# =============================================================================

resource "aws_security_group" "this" {
  name        = "payroll-mail-service-${var.environment}"
  description = "Payroll Mail Service — SSH + app HTTP"

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.ssh_cidr]
  }

  ingress {
    description = "App HTTP"
    from_port   = 3000
    to_port     = 3000
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    description = "All outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# =============================================================================
# AMI — latest Amazon Linux 2023 (x86_64)
# =============================================================================

data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# =============================================================================
# EC2 instance
# =============================================================================

resource "aws_instance" "this" {
  ami                    = data.aws_ami.al2023.id
  instance_type          = var.instance_type
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [aws_security_group.this.id]

  root_block_device {
    volume_type           = "gp3"
    volume_size           = var.root_volume_size_gb
    delete_on_termination = true
    encrypted             = true
  }

  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    git_repo_url      = var.git_repo_url
    git_branch        = var.git_branch
    app_password      = var.app_password
    smtp_host         = var.smtp_host
    smtp_port         = tostring(var.smtp_port)
    smtp_user         = var.smtp_user
    smtp_pass         = var.smtp_pass
    from_email        = var.from_email
    from_name         = var.from_name
    daily_limit       = tostring(var.daily_limit)
    anthropic_api_key = var.anthropic_api_key
  })

  # To re-run setup after changing env vars:
  #   terraform taint aws_instance.this && terraform apply
  user_data_replace_on_change = false

  lifecycle {
    prevent_destroy = false
  }
}

# =============================================================================
# Elastic IP — static address that survives stop/start
# =============================================================================

resource "aws_eip" "this" {
  instance = aws_instance.this.id
  domain   = "vpc"
}
