# =============================================================================
# SSH key pair — generated by Terraform, private key saved as payroll-mail-service.pem
# =============================================================================

resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = "payroll-mail-service-${var.environment}"
  public_key = tls_private_key.this.public_key_openssh

  tags = {
    Name  = "payroll-mail-service-key-pair"
    Owner = "Davide Caputo"
  }
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.this.private_key_pem
  filename        = "${path.module}/payroll-mail-service.pem"
  file_permission = "0600"
}

# =============================================================================
# Security group
# =============================================================================

resource "aws_security_group" "this" {
  name        = "payroll-mail-service-${var.environment}"
  description = "Payroll Mail Service - SSH + app HTTP"

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.ssh_cidr]
  }

  ingress {
    description = "App HTTP"
    from_port   = 3000
    to_port     = 3000
    protocol    = "tcp"
    cidr_blocks = [var.ssh_cidr]
  }

  egress {
    description = "All outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name  = "payroll-mail-service-sg"
    Owner = "Davide Caputo"
  }
}

# =============================================================================
# AMI — latest Amazon Linux 2023 (x86_64)
# =============================================================================

data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# =============================================================================
# EC2 instance
# =============================================================================

resource "aws_instance" "this" {
  ami                    = data.aws_ami.al2023.id
  instance_type          = var.instance_type
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [aws_security_group.this.id]
  iam_instance_profile   = aws_iam_instance_profile.ec2.name

  root_block_device {
    volume_type           = "gp3"
    volume_size           = var.root_volume_size_gb
    delete_on_termination = true
    encrypted             = true

    tags = {
      Name  = "payroll-mail-service-root-volume"
      Owner = "Davide Caputo"
    }
  }

  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    git_repo_url = var.git_repo_url
    git_branch   = var.git_branch
    secret_arn   = aws_secretsmanager_secret.app_config.arn
    aws_region   = var.aws_region
    environment  = var.environment
  })

  user_data_replace_on_change = false

  tags = {
    Name  = "payroll-mail-service"
    Owner = "Davide Caputo"
  }
}

# =============================================================================
# Elastic IP — static address that survives stop/start
# =============================================================================

resource "aws_eip" "this" {
  instance = aws_instance.this.id
  domain   = "vpc"

  tags = {
    Name  = "payroll-mail-service-eip"
    Owner = "Davide Caputo"
  }
}
