# =============================================================================
# SSH key pair — generated by Terraform, private key saved as payroll-mail-service.pem
# =============================================================================

resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = "payroll-mail-service-${var.environment}"
  public_key = tls_private_key.this.public_key_openssh

  tags = {
    Name  = "payroll-mail-service-key-pair"
    Owner = "YOUR_TEAM"
  }
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.this.private_key_pem
  filename        = "${path.module}/payroll-mail-service.pem"
  file_permission = "0600"
}

# =============================================================================
# Security group
# =============================================================================

resource "aws_security_group" "this" {
  name        = "payroll-mail-service-${var.environment}"
  description = "Payroll Mail Service - SSH + app HTTP"

  # No SSH: use SSM Session Manager (aws ssm start-session --target <instance-id>).

  # nginx on the instance terminates TLS (Let's Encrypt); port 80 only redirects.
  # The app itself listens on 127.0.0.1:3000 and is never exposed.
  ingress {
    description = "HTTPS from offices"
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = var.office_cidrs
  }

  ingress {
    description = "HTTP from offices (redirects to HTTPS)"
    from_port   = 80
    to_port     = 80
    protocol    = "tcp"
    cidr_blocks = var.office_cidrs
  }

  egress {
    description = "All outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name  = "payroll-mail-service-sg"
    Owner = "YOUR_TEAM"
  }
}

# =============================================================================
# AMI — latest Amazon Linux 2023 (x86_64)
# =============================================================================

data "aws_ami" "al2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name = "name"
    # Plain AL2023 only — the old "al2023-ami-*" pattern also matched the ECS/Neuron variants.
    values = ["al2023-ami-2023.*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# =============================================================================
# EC2 instance
# =============================================================================

resource "aws_instance" "this" {
  ami                    = data.aws_ami.al2023.id
  instance_type          = var.instance_type
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [aws_security_group.this.id]
  iam_instance_profile   = aws_iam_instance_profile.ec2.name

  root_block_device {
    volume_type           = "gp3"
    volume_size           = var.root_volume_size_gb
    delete_on_termination = true
    encrypted             = true

    tags = {
      Name  = "payroll-mail-service-root-volume"
      Owner = "YOUR_TEAM"
    }
  }

  metadata_options {
    http_tokens   = "required" # IMDSv2 only (matches the live instance)
    http_endpoint = "enabled"
  }

  user_data = templatefile("${path.module}/user_data.sh.tpl", {
    ecr_registry              = split("/", aws_ecr_repository.this.repository_url)[0]
    ecr_repo_url              = aws_ecr_repository.this.repository_url
    image_tag                 = var.image_tag
    secret_arn                = aws_secretsmanager_secret.app_config.arn
    aws_region                = var.aws_region
    environment               = var.environment
    smtp_host_allowlist       = var.smtp_host_allowlist
    payslip_retention_days    = var.payslip_retention_days
    payslip_delete_after_send = var.payslip_delete_after_send
    domain_name               = var.domain_name
    acme_email                = var.acme_email
    nginx_image               = var.nginx_image
    certbot_image             = var.certbot_image
  })

  # A user_data change stops/starts the instance in place (data on the root volume is
  # kept) but cloud-init won't re-run it: re-run it via SSM (see impl notes / scripts/deploy.sh).
  user_data_replace_on_change = false

  lifecycle {
    # The root volume holds the SQLite DB and payslip runs (delete_on_termination = true),
    # so a newer AMI must never force a replacement. Rebuild deliberately instead.
    ignore_changes = [ami]
  }

  tags = {
    Name  = "payroll-mail-service"
    Owner = "YOUR_TEAM"
  }
}

# =============================================================================
# Elastic IP — static address that survives stop/start
# =============================================================================

resource "aws_eip" "this" {
  instance = aws_instance.this.id
  domain   = "vpc"

  tags = {
    Name  = "payroll-mail-service-eip"
    Owner = "YOUR_TEAM"
  }
}
